##please provide the summary_stats prefix for each GWAS, the absolute paths to the summary stats and the top loci files
##and the effective sample size (Neff)

summary_stats_prefix:
  - Mullins_2021
  - Bellenguez_2021_hg19
top_loci_file:
  - /sc/arion/projects/ad-omics/ashvin/finemapping_smk/resources/daner_bip_pgc3_toploci.csv
  - /sc/arion/projects/ad-omics/data/references/GWAS/Bellenguez_hg19/Bellenguez_top_hg19.tsv
full_sumstats:
  - /sc/arion/projects/ad-omics/data/references/GWAS/Daner_2020.processed.tsv.gz
  - /sc/arion/projects/ad-omics/data/references/GWAS/Bellenguez_hg19/processed_updated/Bellenguez_2021_hg19.processed.tsv.gz
N: 
  - 101962
  - 487511
